### ISSUE TITLE
bug: GRPC dependency (SwiftNIO) fails to build on Ubuntu 22.04 with rules_swift_package_manager

### ISSUE THREAD

**Issue by AttilaTheFun** [cgrindel/rules_swift_package_manager#1012]
This issue is causing CI to fail on my PR to add support for the new swift proto library rules:
https://github.com/cgrindel/rules_swift_package_manager/pull/834

Previously, the GRPC example in the repository used the GRPC library and its dependencies that have hardcoded BUILD files in rules_swift. However, when I try to build the same dependencies through rules_swift_package_manager, I get the following compilation error from the NIOPosix library:

```
ubuntu@jammy:~/rules_swift_package_manager/examples/grpc_example$ bazelisk build @swiftpkg_grpc_swift//:GRPC.rspm
WARNING: Option 'experimental_remote_build_event_upload' is deprecated: Use --remote_build_event_upload instead
WARNING: Option 'experimental_remote_build_event_upload' is deprecated: Use --remote_build_event_upload instead
INFO: Analyzed target @@rules_swift_package_manager~~swift_deps~swiftpkg_grpc_swift//:GRPC.rspm (67 packages loaded, 2346 targets configured).
ERROR: /home/ubuntu/.cache/bazel/_bazel_ubuntu/2cab11611dc92fa2f8870ec604258d7f/external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/BUILD.bazel:418:14: Compiling Swift module @@rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio//:NIOPosix.rspm failed: (Exit 1): worker failed: error executing SwiftCompile command (from target @@rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio//:NIOPosix.rspm) 
  (cd /home/ubuntu/.cache/bazel/_bazel_ubuntu/2cab11611dc92fa2f8870ec604258d7f/sandbox/linux-sandbox/993/execroot/_main && \
  exec env - \
    PATH=/bin:/usr/bin:/usr/local/bin \
  bazel-out/aarch64-opt-exec-ST-13d3ddad9198/bin/external/rules_swift~/tools/worker/worker /home/ubuntu/swift-5.9-RELEASE-ubuntu20.04-aarch64/usr/bin/swiftc -emit-object -output-file-map bazel-out/aarch64-fastbuild/bin/external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/NIOPosix.rspm.output_file_map.json -Xfrontend -no-clang-module-breadcrumbs -emit-module-path bazel-out/aarch64-fastbuild/bin/external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/NIOPosix.swiftmodule -enable-bare-slash-regex -DDEBUG -Onone -Xfrontend -no-serialize-debugging-options -enable-testing -gline-tables-only '-Xwrapped-swift=-debug-prefix-pwd-is-dot' '-Xwrapped-swift=-file-prefix-pwd-is-dot' -module-cache-path bazel-out/aarch64-fastbuild/bin/_swift_module_cache -Ibazel-out/aarch64-fastbuild/bin/external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio -Ibazel-out/aarch64-fastbuild/bin/external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_collections -Ibazel-out/aarch64-fastbuild/bin/external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_atomics '-Xwrapped-swift=-macro-expansion-dir=bazel-out/aarch64-fastbuild/bin/external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/NIOPosix.rspm.macro-expansions' -Xcc -iquoteexternal/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio -Xcc -iquotebazel-out/aarch64-fastbuild/bin/external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio -Xcc -iquoteexternal/rules_swift_package_manager~~swift_deps~swiftpkg_swift_atomics -Xcc -iquotebazel-out/aarch64-fastbuild/bin/external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_atomics -Xcc -iquote. -Xcc -iquotebazel-out/aarch64-fastbuild/bin -Xcc -isystemexternal/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/CNIOLinux/include -Xcc -isystembazel-out/aarch64-fastbuild/bin/external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/CNIOLinux/include -Xcc -isystemexternal/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/CNIODarwin/include -Xcc -isystembazel-out/aarch64-fastbuild/bin/external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/CNIODarwin/include -Xcc -isystemexternal/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/CNIOWindows/include -Xcc -isystembazel-out/aarch64-fastbuild/bin/external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/CNIOWindows/include -Xcc -isystemexternal/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/CNIOAtomics/include -Xcc -isystembazel-out/aarch64-fastbuild/bin/external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/CNIOAtomics/include -Xcc -isystemexternal/rules_swift_package_manager~~swift_deps~swiftpkg_swift_atomics/Sources/_AtomicsShims/include -Xcc -isystembazel-out/aarch64-fastbuild/bin/external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_atomics/Sources/_AtomicsShims/include -Xcc '-DSWIFT_PACKAGE=1' -Xcc -D_GNU_SOURCE -Xcc -D__APPLE_USE_RFC_3542 -Xcc -DSWIFT_PACKAGE -Xcc -DCOLLECTIONS_RANDOMIZED_TESTING -Xcc -DATOMICS_NATIVE_BUILTINS -Xcc '-fmodule-map-file=bazel-out/aarch64-fastbuild/bin/external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/CNIOLinux.rspm.swift.modulemap' -Xcc '-fmodule-map-file=bazel-out/aarch64-fastbuild/bin/external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/CNIODarwin.rspm.swift.modulemap' -Xcc '-fmodule-map-file=bazel-out/aarch64-fastbuild/bin/external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/CNIOWindows.rspm.swift.modulemap' -Xcc '-fmodule-map-file=bazel-out/aarch64-fastbuild/bin/external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/CNIOAtomics.rspm.swift.modulemap' -Xcc '-fmodule-map-file=bazel-out/aarch64-fastbuild/bin/external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_atomics/_AtomicsShims.rspm.swift.modulemap' -Xfrontend -color-diagnostics -enable-batch-mode -module-name NIOPosix -DSWIFT_PACKAGE -D_GNU_SOURCE -D__APPLE_USE_RFC_3542 -DSWIFT_PACKAGE -DCOLLECTIONS_RANDOMIZED_TESTING -DATOMICS_NATIVE_BUILTINS -parse-as-library -static external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/BSDSocketAPICommon.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/BSDSocketAPIPosix.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/BSDSocketAPIWindows.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/BaseSocket.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/BaseSocketChannel+SocketOptionProvider.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/BaseSocketChannel.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/BaseStreamSocketChannel.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/Bootstrap.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/ControlMessage.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/DatagramVectorReadManager.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/FileDescriptor.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/GetaddrinfoResolver.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/HappyEyeballs.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/IO.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/IntegerBitPacking.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/IntegerTypes.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/Linux.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/LinuxCPUSet.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/LinuxUring.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/MultiThreadedEventLoopGroup.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/NIOThreadPool.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/NonBlockingFileIO.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/PendingDatagramWritesManager.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/PendingWritesManager.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/PipeChannel.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/PipePair.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/PointerHelpers.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/Pool.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/PooledRecvBufferAllocator.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/PosixSingletons+ConcurrencyTakeOver.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/PosixSingletons.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/RawSocketBootstrap.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/Resolver.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/Selectable.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/SelectableChannel.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/SelectableEventLoop.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/SelectorEpoll.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/SelectorGeneric.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/SelectorKqueue.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/SelectorUring.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/ServerSocket.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/Socket.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/SocketChannel.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/SocketProtocols.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/System.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/Thread.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/ThreadPosix.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/ThreadWindows.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/UnsafeTransfer.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/Utilities.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/VsockAddress.swift external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/VsockChannelEvents.swift)
# Configuration: 7e4d605c18c6d14bc69f79e5b9189680930dd477b6ad51e9ebadb6ed66bbb065
# Execution platform: @@local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/System.swift:105:128: error: cannot convert value of type '(Int32, __SOCKADDR_ARG, UnsafeMutablePointer<socklen_t>?) -> Int32' (aka '(Int32, __SOCKADDR_ARG, Optional<UnsafeMutablePointer<UInt32>>) -> Int32') to specified type '@convention(c) (CInt, UnsafeMutablePointer<sockaddr>?, UnsafeMutablePointer<socklen_t>?) -> CInt' (aka '@convention(c) (Int32, Optional<UnsafeMutablePointer<sockaddr>>, Optional<UnsafeMutablePointer<UInt32>>) -> Int32')
private let sysGetpeername: @convention(c) (CInt, UnsafeMutablePointer<sockaddr>?, UnsafeMutablePointer<socklen_t>?) -> CInt = getpeername
                                                                                                                               ^
external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/System.swift:106:128: error: cannot convert value of type '(Int32, __SOCKADDR_ARG, UnsafeMutablePointer<socklen_t>?) -> Int32' (aka '(Int32, __SOCKADDR_ARG, Optional<UnsafeMutablePointer<UInt32>>) -> Int32') to specified type '@convention(c) (CInt, UnsafeMutablePointer<sockaddr>?, UnsafeMutablePointer<socklen_t>?) -> CInt' (aka '@convention(c) (Int32, Optional<UnsafeMutablePointer<sockaddr>>, Optional<UnsafeMutablePointer<UInt32>>) -> Int32')
private let sysGetsockname: @convention(c) (CInt, UnsafeMutablePointer<sockaddr>?, UnsafeMutablePointer<socklen_t>?) -> CInt = getsockname
                                                                                                                               ^
external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/System.swift:482:33: error: cannot convert value of type 'UnsafePointer<sockaddr>' to expected argument type '__CONST_SOCKADDR_ARG'
            sysBind(descriptor, ptr, socklen_t(bytes))
                                ^
external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/System.swift:531:42: error: cannot convert value of type 'UnsafeMutablePointer<sockaddr>?' to expected argument type '__SOCKADDR_ARG'
            return sysAccept(descriptor, addr, len)
                                         ^
external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/System.swift:545:40: error: cannot convert value of type 'UnsafePointer<sockaddr>' to expected argument type '__CONST_SOCKADDR_ARG'
                sysConnect(descriptor, addr, size)
                                       ^
error: emit-module command failed with exit code 1 (use -v to see invocation)
external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/System.swift:105:128: error: cannot convert value of type '(Int32, __SOCKADDR_ARG, UnsafeMutablePointer<socklen_t>?) -> Int32' (aka '(Int32, __SOCKADDR_ARG, Optional<UnsafeMutablePointer<UInt32>>) -> Int32') to specified type '@convention(c) (CInt, UnsafeMutablePointer<sockaddr>?, UnsafeMutablePointer<socklen_t>?) -> CInt' (aka '@convention(c) (Int32, Optional<UnsafeMutablePointer<sockaddr>>, Optional<UnsafeMutablePointer<UInt32>>) -> Int32')
private let sysGetpeername: @convention(c) (CInt, UnsafeMutablePointer<sockaddr>?, UnsafeMutablePointer<socklen_t>?) -> CInt = getpeername
                                                                                                                               ^
external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_nio/Sources/NIOPosix/System.swift:106:128: error: cannot convert value of type '(Int32, __SOCKADDR_ARG, UnsafeMutablePointer<socklen_t>?) -> Int32' (aka '(Int32, __SOCKADDR_ARG, Optional<UnsafeMutablePointer<UInt32>>) -> Int32') to specified type '@convention(c) (CInt, UnsafeMutablePointer<sockaddr>?, UnsafeMutablePointer<socklen_t>?) -> CInt' (aka '@convention(c) (Int32, Optional<UnsafeMutablePointer<sockaddr>>, Optional<UnsafeMutablePointer<UInt32>>) -> Int32')
private let sysGetsockname: @convention(c) (CInt, UnsafeMutablePointer<sockaddr>?, UnsafeMutablePointer<socklen_t>?) -> CInt = getsockname
                                                                                                                               ^
error: fatalError
Target @@rules_swift_package_manager~~swift_deps~swiftpkg_grpc_swift//:GRPC.rspm failed to build
INFO: Elapsed time: 21.200s, Critical Path: 12.87s
INFO: 47 processes: 35 internal, 12 linux-sandbox.
ERROR: Build did NOT complete successfully
```

You can reproduce this for yourself with the following steps:
1. Set up a Ubuntu 22.04 VM on an ARM Mac (not sure if this is important).
2. Install Swift 5.9 and Bazel(isk). I also had to use clang-14 because of a bug in GCC in clang-13.
3. Build the grpc_example in the rules_swift_package_manager repository and verify that it works.
4. Update the Package.swift to the following and run //:swift_update_pkgs

```
let package = Package(
    name: "grpc_example",
    dependencies: [
        // These are the versions used by rules_swift 1.18.0
        .package(url: "https://github.com/grpc/grpc-swift.git", exact: "1.16.0"),
        .package(url: "https://github.com/apple/swift-protobuf.git", exact: "1.20.2"),
    ]
)
```

5. Try to build the GRPC library with `bazelisk build @swiftpkg_grpc_swift//:GRPC.rspm`

**Comment by AttilaTheFun** [comment]
This was fixed with the alwayslink flag
